#! /bin/sh

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0
bspc monitor DP-5 -d 11 12 13 14 15
bspc monitor DP-2 -d 16 17 18 19 20

bspc config border_width         2
bspc config window_gap          10
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#353b45"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a ckb-next desktop=6
bspc rule -a Brave-browser desktop=6
bspc rule -a discord desktop=1
bspc rule -a Blueberry.py desktop=1

# wmname LG3D &
# bspc rule -a android-studio state=floating border=off follow=on
