#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap          10
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#353b45"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a brave-browser desktop='^5'
bspc rule -a discord desktop='^1'

wmname LG3D &
bspc rule -a android-studio state=floating border=off follow=on
