#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
dunst &
nm-applet &
redshift-gtk &
playerctld daemon &
ckb-next &
~/.local/bin/brave &
discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy &
blueberry &
setxkbmap -option "caps:escape_shifted_capslock" &
xsetroot -cursor_name left_ptr &
picom --experimental-backends

bspc monitor DP-1 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap          10
bspc config normal_border_color "#282c34"
bspc config focused_border_color "#353b45"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a ckb-next desktop=5
bspc rule -a Brave-browser desktop=5
bspc rule -a discord desktop=1
bspc rule -a Blueberry.py desktop=1

# wmname LG3D &
# bspc rule -a android-studio state=floating border=off follow=on
